### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by olivvein** [rscada/libmbus#58]
Good work, for the libmbus.
It works fine in ubuntu.

Have you an idea how to install libmbus on Raspberry Pi (Raspbian ARM)

The basic installation does not work.

I think it would be a perfect fit between an arduino and a pc to handle m-bus data.

**Comment by tnrajvignesh** [comment]
Hi,
I managed to get the libmbus library compiled and working on my pi.
I would like to use the python wrapper [here](https://github.com/rscada/python-mbus)
to develop my Mbus scanner application on Python.
The example code is [here](https://github.com/rscada/python-mbus/blob/master/examples/mbus-test-1.py)

In the example code, I see an Mbus instance being initialised in line 16
mbus = MBus(host="mbus-gw1", port=8888)

I would like to have Mbus on serial port /dev/TTYAMA0.
Please guide me on initialising Mbus on the serial port instead of TCP.
